import { Badge } from '@/components/ui/badge'
import { LinkButton } from '@/components/ui/button'
import type { FixtureWithTeam } from '@/lib/data/types'
import { formatMatchDate, formatMatchTime, getFixturePresentation } from '@/lib/formatters/fixtures'

export function AdminFixtureList({ fixtures }: { fixtures: FixtureWithTeam[] }) {
  return <div className="mt-6"><div className="hidden overflow-x-auto border border-border bg-surface md:block"><table className="w-full min-w-[58rem] text-left text-sm"><thead className="bg-surface-muted text-xs uppercase text-muted-foreground"><tr>{['Match','Date','Competition','Side','Score','Status','Actions'].map(h=><th className="px-4 py-3" key={h}>{h}</th>)}</tr></thead><tbody className="divide-y divide-border">{fixtures.map(f=><tr key={f.id}><td className="px-4 py-3 font-semibold">{f.team.name} vs {f.opponent_name}</td><td className="px-4 py-3">{formatMatchDate(f.match_date)}<br/><span className="text-muted-foreground">{formatMatchTime(f.match_date)}</span></td><td className="max-w-48 break-words px-4 py-3">{f.competition||'-'}</td><td className="px-4 py-3 capitalize">{f.home_or_away}</td><td className="px-4 py-3 font-bold tabular-nums">{score(f)}</td><td className="px-4 py-3"><Status value={f.status}/></td><td className="px-4 py-3"><LinkButton href={`/admin/fixtures/${f.id}/edit`} size="sm" variant="outline">Edit</LinkButton></td></tr>)}</tbody></table></div>
  <div className="grid gap-4 md:hidden">{fixtures.map(f=><article className="border border-border bg-surface p-4" key={f.id}><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase text-success">{f.team.name} / {f.home_or_away}</p><h2 className="mt-2 break-words font-bold">{f.opponent_name}</h2></div><Status value={f.status}/></div><p className="mt-4 text-sm">{formatMatchDate(f.match_date)} at {formatMatchTime(f.match_date)}</p><p className="mt-1 break-words text-sm text-muted-foreground">{f.competition||'Competition not provided'} / {f.venue||'Venue not provided'}</p><p className="mt-4 text-lg font-black">{score(f)}</p><LinkButton className="mt-4" href={`/admin/fixtures/${f.id}/edit`} size="sm" variant="outline">Edit Fixture</LinkButton></article>)}</div></div>
}
function score(f:FixtureWithTeam){if(f.status!=='completed')return'-';const p=getFixturePresentation(f);return `${p.home.name} ${p.home.score} - ${p.away.score} ${p.away.name}`}
function Status({value}:{value:string}){const variant=value==='completed'?'success':value==='cancelled'?'danger':value==='postponed'?'warning':'neutral';return <Badge variant={variant} className="capitalize">{value}</Badge>}
